### ISSUE TITLE
.redact-pii/google-account-placeholder-key.json

### ISSUE THREAD

**Issue by brandonros** [solvvy/redact-pii#13]
Why?...

Error: ENOENT: no such file or directory, open '/home/brandon/.redact-pii/google-account-placeholder-key.json'

Just scrub PII, don't try to solve the world.

**Comment by patrickhulce** [comment]
hey @brandonros, no clue are you sure that's this repo? the code is pretty small, has no such file read, and I have no similar files/errors https://github.com/solvvy/redact-pii/blob/e6880119d8ce80a0df8cfe25e0b356d5019208e8/lib/index.js#L1-L65

**Comment by brandonros** [comment]
Yes.

They updated it on gitlab so that when you do

npm install redact-pii

you don't get this version

You get a wild steaming piece of shit version that even if you don't specify to turn on some Google data loss shit, it looks for a file and crashes on error.

Solid, solid coding.

By the way, this README is out of date, kind of.

Out of date in the sense that,

if you `npm install redact-pii`, the new version returns a Promise, and not a string.
