### ISSUE TITLE
Looking for Google key file tho online option is not enabled.

### ISSUE THREAD

**Issue by avnish-si** [solvvy/redact-pii#14]
I haven't enabled Google service still getting the error below. Please help.

`(node:81118) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, open '/Users/abnishsingh/.redact-pii/google-account-placeholder-key.json'`

**Comment by archerking** [comment]
also ` '/Users/abnishsingh/.redact-pii/google-account-placeholder-key.json'` path is not correct. Unnecessarily initializing Google dlp class tho online option is set top false.

**Comment by acnwucker** [comment]
this is fixed now in version 2.0.6
