### ISSUE TITLE
Confusing README requires update

### ISSUE THREAD

**Issue by James-Firth** [solvvy/redact-pii#20]
The [github readme](https://github.com/solvvy/redact-pii/blob/master/README.md) says

> This repository has moved to gitlab. Please clone and fork from there. All future work will occur in gitlab and will be mirrored here.

Which I believe should be removed based on the activity of both repos.

 However, if I didn't notice how recent the latest commits were I'd follow the link to [gitlab](https://gitlab.com/solvvy/redact-pii) (which I just did) and I'll find

>  This repository has moved back to github. Please clone and send PRs / MRs there. The gitlab repo 
will not be updated anymore.

Which is rather confusing.

**Comment by acnwucker** [comment]
@James-Firth Apologies for the confusion, this is fixed now.
